#import "NativeOrderbookEngine.h"
#include "OrderbookEngine.h"

@implementation NativeOrderbookEngine {
  turbobook::OrderbookEngine _engine;
}

// Registers the module as "OrderbookEngine" — matches TurboModuleRegistry.get("OrderbookEngine") in JS.
RCT_EXPORT_MODULE(OrderbookEngine)

- (void)processSnapshot:(NSArray<NSNumber *> *)data {
  NSUInteger len = data.count;
  std::vector<std::tuple<double, int, double>> entries;
  entries.reserve(len / 3);
  for (NSUInteger i = 0; i + 2 < len; i += 3) {
    entries.emplace_back(data[i].doubleValue, data[i + 1].intValue, data[i + 2].doubleValue);
  }
  _engine.processSnapshot(entries);
}

- (void)processDelta:(double)price count:(double)count amount:(double)amount {
  _engine.processDelta(price, static_cast<int>(count), amount);
}

- (void)reset {
  _engine.reset();
}

- (NSDictionary *)getTopLevels:(double)n {
  auto top = _engine.getTopLevels(static_cast<int>(n));

  auto buildArray = ^NSArray *(const std::vector<turbobook::LevelWithTotal> &levels) {
    NSMutableArray *arr = [NSMutableArray arrayWithCapacity:levels.size()];
    for (const auto &l : levels) {
      [arr addObject:@[ @(l.price), @(l.count), @(l.amount), @(l.total) ]];
    }
    return arr;
  };

  return @{@"bids" : buildArray(top.bids), @"asks" : buildArray(top.asks)};
}

- (double)getChecksum {
  return static_cast<double>(_engine.getChecksum());
}

// Provides the JSI bridge generated by codegen (NativeOrderbookEngineSpecJSI).
- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:
    (const facebook::react::ObjCTurboModule::InitParams &)params {
  return std::make_shared<facebook::react::NativeOrderbookEngineSpecJSI>(params);
}

@end
